addSbtPlugin("org.scalastyle"       %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("com.eed3si9n"          % "sbt-assembly"          % "2.3.1")
addSbtPlugin("com.timushev.sbt"      % "sbt-updates"           % "0.6.4")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"          % "2.5.4")
addSbtPlugin("org.scalaxb"           % "sbt-scalaxb"           % "1.8.1")
addSbtPlugin("com.github.sbt"        % "sbt-native-packager"   % "1.11.7")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"            % "7.4.0")
